project_id = "extkotvjigtswrrnxikw"

[functions]
[functions.send-ticket-email]
verify_jwt = false
[functions.send-edit-link]
verify_jwt = false
[functions.notify-complete]
verify_jwt = false
[functions.send-outreach-email]
verify_jwt = false
[functions.get-public-form]
verify_jwt = false