[phases.setup]
nixpkgsArchive = "51ad838b03a05b1de6f9f2a0fffecee64a9788ee"

[phases.install]
cmds = ["npm ci --include=optional"]

[phases.caddy]
nixpkgsArchive = "51ad838b03a05b1de6f9f2a0fffecee64a9788ee"

[staticAssets]
Caddyfile = '''
{
	admin off
	persist_config off
	auto_https off
	log {
		format json
	}
	servers {
		trusted_proxies static private_ranges 100.0.0.0/8
	}
}

:{$PORT:3000} {
	log {
		format json
	}

	root * ../app/{$NIXPACKS_SPA_OUTPUT_DIR}
	encode gzip

	@assets path /assets/*
	header @assets Cache-Control "public, max-age=31536000, immutable"

	handle /assets/* {
		file_server
	}

	@notAssets {
		not path /assets/*
	}
	header @notAssets Cache-Control "no-cache, no-store, must-revalidate"

	handle {
		try_files {path} /index.html
		file_server
	}
}
'''
